# Generated by Django 3.1.7 on 2021-04-17 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_listener_speaker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speaker',
            name='speakers',
        ),
        migrations.DeleteModel(
            name='Listener',
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
